apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    name: alertmanager-deployment
  name: alertmanager
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - image: reg.changhong.io/k8s1.9/alertmanager:v0.16.1
        name: alertmanager
        args:
        - "--config.file=/etc/alertmanager/config.yml"
        - "--storage.path=/alertmanager"
        - "--log.level=debug"
        ports:
        - containerPort: 9093
          protocol: TCP
          name: http
        volumeMounts:
        - name: alertmanager-volume
          mountPath: /etc/alertmanager
        - name: mails-volume
          mountPath: /etc/mails
        - name: zone
          mountPath: /etc/localtime
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 600Mi

      serviceAccountName: prometheus    
      volumes:
      - name: data
        emptyDir: {}
      - name: alertmanager-volume
        configMap:
          name: alertmanager
      - name: mails-volume
        configMap:
          name: mails
      - name: zone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
