kind: ConfigMap
apiVersion: v1
metadata:
  name: mails
  namespace: prometheus
data:
  mail.tmpl: |
    {{ define "alert.html" }}
    <h1> 监控告警通知 </h1>
    {{ range $i, $alert := .Alerts }}
    <hr />
    <pre>
        告警级别: {{ index $alert.Annotations "levelstr" }} 
        发生时间: {{ $alert.StartsAt.Local.String }} 
        结束时间: {{ if $alert.EndsAt.IsZero }} / {{else}} {{ $alert.EndsAt.Local.String }} {{ end }} 
        触发规则: {{ index $alert.Annotations "description" }} 
        规则描述: {{ index $alert.Annotations "timestr" }} 
        告警对象: {{ index $alert.Annotations "target" }} 
        所属区域: {{ index $alert.Annotations "aid" }} 
    </pre>
    {{ end }}
    {{ end }}
